<?php

/**
 * Model_Base_Character
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user
 * @property integer $experience
 * @property integer $class
 * @property integer $kingdom
 * @property Model_Class $Class
 * @property Model_User $User
 * @property Doctrine_Collection $Announcement
 * @property Doctrine_Collection $Mail
 * @property Doctrine_Collection $Mail_2
 * @property Doctrine_Collection $News
 * @property Doctrine_Collection $News_2
 * @property Doctrine_Collection $Resources
 * @property Doctrine_Collection $Workers
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Character extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('character');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('user', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('experience', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('class', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('kingdom', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Class as Class', array(
             'local' => 'class',
             'foreign' => 'id'));

        $this->hasOne('Model_User as User', array(
             'local' => 'user',
             'foreign' => 'id'));

        $this->hasMany('Model_Announcement as Announcement', array(
             'local' => 'id',
             'foreign' => 'user'));

        $this->hasMany('Model_Mail as Mail', array(
             'local' => 'id',
             'foreign' => 'to'));

        $this->hasMany('Model_Mail as Mail_2', array(
             'local' => 'id',
             'foreign' => 'from'));

        $this->hasMany('Model_News as News', array(
             'local' => 'id',
             'foreign' => 'to'));

        $this->hasMany('Model_News as News_2', array(
             'local' => 'id',
             'foreign' => 'from'));

        $this->hasMany('Model_Resources as Resources', array(
             'local' => 'id',
             'foreign' => 'id'));

        $this->hasMany('Model_Workers as Workers', array(
             'local' => 'id',
             'foreign' => 'id'));
    }
}