<?php

/**
 * Model_Character
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Character extends Model_Base_Character
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Resources as resources', array(
             'local' => 'id',
             'foreign' => 'id'));

        $this->hasOne('Model_Workers as workers', array(
             'local' => 'id',
             'foreign' => 'id'));
    }
}